# Generated by Django 4.2.30 on 2026-05-23 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(default='P', max_length=2)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='estudiantes.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('documento', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('asistencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='justificacion', to='asistencia.asistencia')),
            ],
        ),
    ]
