# Generated by Django 4.2.30 on 2026-05-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='DNI'),
        ),
    ]
