# Generated by Django 4.2.30 on 2026-05-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('apoderados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoderado',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='apoderado',
            name='estudiantes',
            field=models.ManyToManyField(related_name='apoderados', to='estudiantes.estudiante'),
        ),
    ]
